[project]

name = "hyperloglog"
version = "0.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Hyperloglog implementation in Rust"
license = "ISC"

[lib]

name = "hyperloglog"
path = "src/hyperloglog/lib.rs"
