[project]
name = "hyperloglog"
version = "0.0.7"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Hyperloglog implementation in Rust"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-hyperloglog"
repository = "https://github.com/jedisct1/rust-hyperloglog"

[lib]
name = "hyperloglog"
path = "src/hyperloglog/lib.rs"

[dependencies.rand]
rand = "*"
